find_upcoming_events(): Try to parse data from the Meetup API
* Clone the token so we can use it without a borrow error
* Get the response text from our request to the API and try to parse it

This gives me the following panic:

      thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
      value: ErrorImpl { code: Message("invalid type: null, expected a
      sequence"), line: 0, column: 0 }', libcore/result.rs:945:5

Still trying to figure out where my problem is.