meetup_rss(description_header): Improve string join section
Instead of the verbose and unclear appending, use a `join` to add the
newline. Filter out empty strings to ensure the newline doesn't get
added if any of `where` or `place` are empty.

Needed to convert the slice strings to owned strings to deal with this
error:

    error[E0599]: no method named `join` found for type `std::vec::Vec<&std::string::String>` in the current scope
      --> src/meetup_rss.rs:92:10
       |
    92 |         .join("\n")
       |          ^^^^